### ISSUE TITLE
How to change the number of time steps?

### ISSUE THREAD

**Issue by arianabrenner** [lequieu/1cpn-model#5]
I followed the Quickstart guide and was excited to see the output!  How can I change the number of time-steps to run longer trajectories? The default seems to be ~20 timepoints.

**Comment by arianabrenner** [comment]
Never mind.  I now see that I can just change the "run" variable in the last line of the in.1cpn file.

**Comment by lequieu** [comment]
Perfect! Glad you figured it out!
